name: vss
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python
  - nltk=3.6.7=pyhd8ed1ab_0  
  - numpy
  - scipy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - jupyter_nbextensions_configurator
  - tk
  - pip
  - pip:
    - svgling
    - gensim==4.1.2
    
